server:
  port: 8080
netty:
  port: 4001
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false # 禁止大写变小写时自动添加下划线
spring:
  datasource:
    dynamic:
      primary: dateService #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        shp: # 数据源1
          url: jdbc:postgresql://127.0.0.1:5432/xtd_cpga_shp?charSet=UTF-8
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver
        dateService:
          url: jdbc:postgresql://127.0.0.1:5432/xtd_ybls_dateservice?charSet=UTF-8
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver
        test:
          url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
      durid:
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
  autoconfigure:
    exclude:  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid配置







































